### ISSUE TITLE
Bug: dataset list --id option throws error

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#1159]
## Bug Description
Get this error testing on Nonprod

```
bill@bill-VirtualBox:~$ geostore dataset create --title bill_test_cli_002 --description "just a test"01FKY474EQ71EY225NEGMKDPE1
bill@bill-VirtualBox:~$ geostore dataset list
Victors-01F8V9S9CDSV5F5GDM16PFSG6Z
MITCHELL_TEST-01FKM5RJQY78RWG2F6ZNX4JNM2
test_1625615792-01F9Z40ZWJCAT1HGN4EAT707QR
test_1625622377-01F9ZA9ZZZDM815S20EHXEAT40
test_1625615765-01F9Z406N21T1HCTWAWS61ANW4
QvQWd2UrHEIy9Rw6SgmM-01FKMAAVW613GK93YCCCTE5DGG
XUDc5K1J0tOx1SBOKlVB-01FKMAB4NFTQFMJBZYBX370PQX
Temp_674-01F72DFHXQ3815A9V1KQ4FJGYV
MITCHELL_TEST2-01FKM5VADN5FPW6BF1JD26D6QJ
Temp04-01F660WG524BZ9E87XQD3F4DGP
bill_test_cli_002-01FKY474EQ71EY225NEGMKDPE1
test_1625629361-01F9ZGZ4EGEZ9R4Z48VNQHKB0Z
topo_pystac_update_test_1631572157-01FFGMEWFBBY7XRZ6659EAWP9W
Temp03-01F660SGA5V20SEQDVCHNGYM1Q
STAC_version_pystac_test-01FBR6M36HT87ZAFYP5H88SEGK
Taranaki_2020-01F9ZFRK12V0WFXJ94S0DHCP65
Auckland2022-01F6KC40E4DH9WZ0SQ73RBG4EC
Assume-role-test-01-01F9JKB6KX6NDZTCJW82G8ZMNG
test_1625615965-01F9Z468N8YDMQE635ETVVYEN9
topo-pystac-upgrade-test_1631490603-01FFE6P1PKESC65AVSCFP0A1M6
update-pystac-test_1631492466-01FFE8EVM8PMVEPBQZ230RGQS8
bill_test_cli_001-01FKY43SXAHRYPZA97P8DWA7RS
Wellington_2020-01FACDTZWA6N2W9NVFEA30T57A
test_1625618828-01F9Z6XNZ89NQXP6P64FC1T7A5
update-pystac-test_1631491795-01FFE7TD5RW2E10TDVQQZS1BAN
test_1625615974-01F9Z46H545MXFEKMRSJVYARJJ
update-pystac-test2_1631494093-01FFEA0HV82812WW4KXBRAVJV9
5c27GmQRe1z94OcIoLXy-01FKMABJ616AJ6D0EM0Z3VYEEP
Auckland2024-01F6N9HFWMQRDKN94J0X2JHF57
test_1626227298-01FAHB6PXJ2T8K5MXKZ7C3A11K
Temp02-01F5YP9V5M0QVA4CT5W0PC35CT
Auckland2021-01F6KB7WPS2TXCDQSQYQHEF3TQ
Temp01-01F5YP998GGJPNVCP12QMM2XTE
test_1631492417-01FFE8DD7EQ8K6YEDWAXNDKQB9
pr30HN2mW71ihMHN-tG0-01FKMABP46Q1WQ2WBTKS1K4F8T
bill@bill-VirtualBox:~$ geostore dataset list --id bill_test_cli_002-01FKY474EQ71EY225NEGMKDPE1
Traceback (most recent call last):
  File "/home/bill/.local/bin/geostore", line 8, in <module>
    sys.exit(app())
  File "/home/bill/.local/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/bill/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/bill/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/bill/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bill/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bill/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bill/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/bill/.local/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/bill/.local/lib/python3.8/site-packages/geostore/cli.py", line 73, in dataset_list
    handle_api_request({HTTP_METHOD_KEY: "GET", BODY_KEY: body}, get_output)
  File "/home/bill/.local/lib/python3.8/site-packages/geostore/cli.py", line 107, in handle_api_request
    output = get_output(response_payload[BODY_KEY])
  File "/home/bill/.local/lib/python3.8/site-packages/geostore/cli.py", line 68, in get_single_output
    return f"{response_body['title']}{DATASET_KEY_SEPARATOR}{response_body['id']}"
KeyError: 'title'

```

## How to Reproduce

1. Do see cli output above
1. Run `…`

What did you expect to happen? 

What actually happened? 

## Software Context

Operating system: Ubuntu 20

Environment: nonprod

Relevant software versions: 

- AWS CLI: 
- Poetry: 

#### Definition of Done

- [ ] This bug is **done**:
  - [ ] Bug resolved to **user's** satisfaction
  - [ ] Automated tests are passing
  - [ ] Code is peer reviewed and pushed to master
  - [ ] Deployed successfully to test environment
  - [ ] Checked against [CODING guidelines](https://github.com/linz/geostore/blob/master/CODING.md)
  - [ ] Relevant new tasks are added to backlog and communicated to the team
  - [ ] Important decisions recorded in the issue ticket
  - [ ] Readme/Changelog/Diagrams are updated
  - [ ] Product Owner has approved as complete
  - [ ] No regression to functional or
        [non-functional](https://github.com/linz/geostore/blob/master/.github/ISSUE_TEMPLATE/user_story.md)
        requirements

**Comment by l0b0** [comment]
You need to pass the dataset ID, not the name, as in `geostore dataset list --id 01FKY474EQ71EY225NEGMKDPE1`. Also, using the latest version I get a more useful message:

```console
$ geostore dataset list --id bill_test_cli_002-01FKY474EQ71EY225NEGMKDPE1
{"message": "Not Found: dataset 'bill_test_cli_002-01FKY474EQ71EY225NEGMKDPE1' does not exist"}
```

**Comment by l0b0** [comment]
Are you using the latest version, 0.1.7? You should be able to run `geostore --version` on that to print the version number.

**Comment by billgeo** [comment]
Pip can't seem to find v0.1.7? 

```
bill@bill-VirtualBox:~$ pip3 install -U geostore==0.1.7
ERROR: Could not find a version that satisfies the requirement geostore==0.1.7 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6)
ERROR: No matching distribution found for geostore==0.1.7
```

**Comment by l0b0** [comment]
Oh, interesting! I guess we need to do a release :grin:. Do you want to do the honors, @MitchellPaff?

**Comment by billgeo** [comment]
Closing
